# Generated by Django 5.0.6 on 2024-06-27 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Category',
        ),
    ]
